name: deploy_frontend
# Deploy when push is made from the frontend folder

on:
    push:
        branches: [ main ]
        paths:
        - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.49.0
        inlineScript: |
            az storage blob upload-batch --account-name azresumest1131 -d '$web' -s frontend/
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.49.0
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "az-resume-cdn" --name "az-resume-cdn" --resource-group "az-resume-rg1"

  # Azure logout
    - name: logout
      run: |
            az logout
